apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "blog.fullname" . }}
