---
resources:
  - ../base

namespace: blog-production

images:
  - name: ghcr.io/blog-frontend
    newName: ghcr.io/blog-frontend
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: blog
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: www.eden-reich.com
