# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

env:
  TAG: $(git rev-parse --short HEAD)

jobs:
  build:
    runs-on:
      - self-hosted
      - k8s
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          TAG=${{ env.TAG }} make package
          TAG=${{ env.TAG }} make push
